From docker.elastic.co/kibana/kibana:5.3.0

ADD ./images/logo.svg /usr/share/kibana/src/ui/public/images/kibana.svg
ADD ./js/refresh_intervals.js /usr/share/kibana/src/ui/public/timepicker/refresh_intervals.js
RUN rm -rf /usr/share/kibana/optimize/bundles/*
