From docker.elastic.co/kibana/kibana:5.3.0

ADD ./images/homesense-logo-text.svg /usr/share/kibana/src/ui/public/images/homesense-logo-text.svg
ADD ./patches/homesense-kibana.patch /usr/share/kibana/homesense-kibana.patch
RUN patch -p1 < homesense-kibana.patch
RUN rm -rf /usr/share/kibana/optimize/bundles/*
